### ISSUE TITLE
naive datetime warning

### ISSUE THREAD

**Issue by shadowfax-chc** [ambitioninc/django-dynamic-initial-data#22]
I am seeing warnings like the following

     RuntimeWarning: DateTimeField RegisteredForDeletionReceipt.register_time received a naive datetime (2015-04-02 23:39:29.416573) while time zone support is active.

They seem to be due to the call to `datetime.utcnow()` [here](https://github.com/ambitioninc/django-dynamic-initial-data/blob/develop/dynamic_initial_data/base.py#L161). 

Using Django's [timezone.now()](https://docs.djangoproject.com/en/1.6/topics/i18n/timezones/#naive-and-aware-datetime-objects) seems like the solution.

**Comment by jaredlewis** [comment]
@shadowfax-chc this has been updated in version 0.5.1. Thanks!
